/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDecorativeElementDialog: typeof import('./src/components/dialog/addDecorativeElementDialog.vue')['default']
    AddProductDialog: typeof import('./src/components/dialog/addProductDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CustomSnackbar: typeof import('./src/components/CustomSnackbar.vue')['default']
    Definitive: typeof import('./src/components/Definitive.vue')['default']
    DragAndDropShelf: typeof import('./src/components/dragAndDropShelf.vue')['default']
    EditProductDialog: typeof import('./src/components/dialog/editProductDialog.vue')['default']
    EditShelfDialog: typeof import('./src/components/dialog/editShelfDialog.vue')['default']
    ExampleFive: typeof import('./src/components/ExampleFive.vue')['default']
    ExampleFour: typeof import('./src/components/ExampleFour.vue')['default']
    ExampleOne: typeof import('./src/components/ExampleOne.vue')['default']
    ExampleSix: typeof import('./src/components/ExampleSix.vue')['default']
    ExampleThree: typeof import('./src/components/ExampleThree.vue')['default']
    ExampleTwo: typeof import('./src/components/ExampleTwo.vue')['default']
    ImportProductDialog: typeof import('./src/components/dialog/importProductDialog.vue')['default']
    LoadingState: typeof import('./src/components/loadingState.vue')['default']
    ResultDialog: typeof import('./src/components/dialog/resultDialog.vue')['default']
    WelcomeDialog: typeof import('./src/components/dialog/welcomeDialog.vue')['default']
  }
}
